services:
  backend:
    build:
     context: ./APIProject
    image: python:3.10
    container_name: django_backend
    command: >
      sh -c "pip install -r requirements.txt &&
             python manage.py showmigrations
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./APIProject:/app

    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=APIProject.settings
    networks:
      - app-network

  frontend:
    image: node:16
    container_name: angular_frontend
    working_dir: /app
    volumes:
      - ./Site:/app
    command: >
      sh -c "npm install &&
             npm run start -- --host 0.0.0.0 --port 4200"
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: python:3.10
    container_name: sqlite_db
    volumes:
      - ./backend/db:/data/db
    command: tail -f /dev/null
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
