# Generated by Django 5.1.1 on 2024-09-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dias_fecha_previa_igual', models.IntegerField()),
                ('dias_fecha_previa_igual_con_reinversion', models.IntegerField()),
                ('dias_horario_posterior_igual', models.IntegerField()),
                ('dias_horario_posterior_igual_con_reinversion', models.IntegerField()),
            ],
        ),
    ]
