# Generated by Django 5.1.1 on 2024-09-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_diaferiado'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaferiado',
            name='descripcion',
            field=models.CharField(default='Dia deriado', max_length=60),
        ),
    ]
