# Generated by Django 5.1.1 on 2024-09-22 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_diaferiado_descripcion'),
    ]

    operations = [
    ]
