# Generated by Django 5.1.1 on 2024-09-22 02:10

from django.db import migrations, models
from ..models import Producto


def create_initial_data(apps, schema_editor):
    Producto1 = apps.get_model('api', 'Producto')

    Producto.objects.create(dias_fecha_previa_igual=2, 
                            dias_fecha_previa_igual_con_reinversion=1,
                            dias_horario_posterior_igual = 3,
                            dias_horario_posterior_igual_con_reinversion = 2
                            )


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240922_0209'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
