# Generated by Django 5.1.1 on 2024-09-22 02:17

from django.db import migrations
from ..models import DiaFeriado
from datetime import date

def create_initial_data(apps, schema_editor):
    DiaFeriado1 = apps.get_model('api', 'DiaFeriado')

    DiaFeriado.objects.create(descripcion='Dia de la restauracion', 
                              fecha= date(2022, 7,12)
                            )
    
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240922_0210'),
    ]

    operations = [
         migrations.RunPython(create_initial_data),
    ]
