# Generated by Django 5.1.1 on 2024-09-22 02:23

from django.db import migrations
from django.contrib.auth import get_user_model

def create_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser(
        username='alpha', 
        email='alpha@alphainversiones.com', 
        password='alpha123@'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240922_0217'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
